---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uctf-ch-lending-pool
  name: uctf-ch-lending-pool
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uctf-ch-lending-pool
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uctf-ch-lending-pool
    spec:
      containers:
        - name: lending-pool
          image: registry.uctf.ir/youngmind1/lending-pool-ctf:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1000m"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: "1000m"
              ephemeral-storage: 1Gi
              memory: 1Gi
          terminationMessagePath: /var/log/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: uctf-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: uctf-ch-lending-pool
spec:
  selector:
    app: uctf-ch-lending-pool
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uctf-ch-lending-pool
  labels:
    app: uctf-ch-lending-pool
  annotations:
spec:
  host: lending.uctf.ir
  port:
    targetPort: 80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: uctf-ch-lending-pool
    weight: 100
  wildcardPolicy: None
