---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uctf-ch-htaccess
  name: uctf-ch-htaccess
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uctf-ch-htaccess
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uctf-ch-htaccess
    spec:
      containers:
        - name: httpd
          image: registry.uctf.ir/ata/htaccess-ctf:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 512Mi
            requests:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 512Mi
          terminationMessagePath: /var/log/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: uctf-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: uctf-ch-htaccess
spec:
  selector:
    app: uctf-ch-htaccess
  ports:
    - port: 80
      targetPort: 80
