version: '3'

services:
  php:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
