---
apiVersion: v1
kind: Secret
metadata:
  name: uctf-ch-the-void-hs-key
stringData:
  key: PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACYeChL/WetqehyLhNBKVQ5WAP5FaVYJbBFLr2LqJEkTAPS1ZRlIf3jSmGWt+z0OF4Y6+8GkIJroQRvMVuNJejD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uctf-ch-the-void-front
  name: uctf-ch-the-void-front
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uctf-ch-the-void-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uctf-ch-the-void-front
    spec:
      containers:
        - name: front
          image: registry.uctf.ir/mehrzad/the-void-front:0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
            requests:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /var/log/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: uctf-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uctf-ch-the-void-hs
  name: uctf-ch-the-void-hs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uctf-ch-the-void-hs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uctf-ch-the-void-hs
    spec:
      containers:
        - name: hs
          image: registry.uctf.ir/mehrzad/t-hs:0.1
          imagePullPolicy: Always
          env:
            - name: TOR_HS_LISTEN_PORT
              value: "80"
            - name: TOR_HS_DEST_ADDR
              value: "uctf-ch-the-void-front:80"
            - name: TOR_HS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: uctf-ch-the-void-hs-key
                  key: key
            - name: TOR_HS_NON_ANON
              value: "1"
          resources:
            limits:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
            requests:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /var/log/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: uctf-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: uctf-ch-the-void-front
spec:
  selector:
    app: uctf-ch-the-void-front
  ports:
    - port: 80
      targetPort: 80
