---
apiVersion: v1
kind: Secret
metadata:
  name: uctf-ch-license-please-secret
stringData:
  flag: uctf{m4yu5h11_15_my_w41fu}
  privkay: ZTWAcGVGl2IFjnFAdH1CeYqSHqUGuoLdReJuBdcbPKo
  pubkey_x: 6lpiwqx45LLPR25UIIYuF2wTTs9seLy3iUA6OYY50kE
  pubkey_y: jY7XafkM60dARvfIIXuNsKIDgqljfYkgN1AFLyPSJtw

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uctf-ch-license-please
  name: uctf-ch-license-please
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uctf-ch-license-please
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uctf-ch-license-please
    spec:
      containers:
        - name: lplz
          image: registry.uctf.ir/mehrzad/license-please:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmprun
              mountPath: /var/run/apache2/
          env:
            - name: LPLZ_FLAG
              valueFrom:
                secretKeyRef:
                  name: uctf-ch-license-please-secret
                  key: flag
            - name: LPLZ_PRIVKEY
              valueFrom:
                secretKeyRef:
                  name: uctf-ch-license-please-secret
                  key: privkay
            - name: LPLZ_PUBKEY_X
              valueFrom:
                secretKeyRef:
                  name: uctf-ch-license-please-secret
                  key: pubkey_x
            - name: LPLZ_PUBKEY_Y
              valueFrom:
                secretKeyRef:
                  name: uctf-ch-license-please-secret
                  key: pubkey_y
          resources:
            limits:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
            requests:
              cpu: "200m"
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /var/log/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: uctf-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmprun
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: uctf-ch-license-please
spec:
  selector:
    app: uctf-ch-license-please
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uctf-ch-license-please
  labels:
    app: uctf-ch-license-please
  annotations:
spec:
  host: lplz.uctf.ir
  port:
    targetPort: 80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: uctf-ch-license-please
    weight: 100
  wildcardPolicy: None
